# Generated by Django 5.2.4 on 2025-07-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_horario_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='timeentry',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
