# Generated by Django 5.2.4 on 2025-07-20 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_horario_app', '0002_alter_timeentry_options_timeentry_is_edited_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntryModificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_start_time', models.DateTimeField()),
                ('requested_end_time', models.DateTimeField(blank=True, null=True)),
                ('requested_break_start', models.DateTimeField(blank=True, null=True)),
                ('requested_break_end', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Razón para la solicitud de cambio.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('original_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_requests', to='control_horario_app.timeentry')),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_modification_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_modification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
