# Generated by Django 5.2.4 on 2025-07-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_horario_app', '0003_timeentrymodificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentrymodificationrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notas del administrador al revisar la solicitud.', null=True),
        ),
    ]
